# Generated by Django 4.2.3 on 2023-11-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limonmentalApp", "0002_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Psychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tipo_consulta", models.CharField(max_length=50)),
                ("especialidad", models.CharField(max_length=50)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("correo", models.EmailField(max_length=254)),
                ("numero", models.CharField(max_length=15)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="psychologists_photos/"
                    ),
                ),
            ],
        ),
    ]
