# Generated by Django 4.2.3 on 2023-12-01 14:52

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):
    dependencies = [
        ("limonmentalApp", "0003_psychologist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologist",
            name="correo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to="psychologists_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="precio",
            field=models.CharField(max_length=20),
        ),
    ]
